---
name: Docker
on:
  push:
    branches: [master]
  pull_request:
jobs:
  # build job
  build:
    name: Build
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        go: ["1.18"]
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup docker buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: |
          image=moby/buildkit:master
          network=host

    - name: Login to GitHub Docker registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build docker image
      run: |
        make docker-buildx-build \
          DOCKER_BUILD_GO_VERSION=${{ matrix.go }} \
          DOCKER_BUILD_VERSION=$(git describe --always --tags --dirty --broken)-go${{ matrix.go }}
